plugins {
    id 'eclipse'
    id 'net.neoforged.moddev' version '2.0.107'
}

version = '1.0'
base.archivesName = "modid"

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = "21.1.190"

    runs {
        client {
            client()

            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.each { arg ->
                    jvmArgument(arg)
                }
            }
        }
        server {
            server()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            logLevel = org.slf4j.event.Level.DEBUG
        }
    }

    mods {
        mcreator {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    // Put repositories for dependencies here
    // ForgeGradle automatically adds the Forge maven and Maven Central for you
    maven { url "https://www.cursemaven.com" }
    // If you have mod jar dependencies in ./libs, you can declare them as a repository like so.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:flat_dir_resolver
    // flatDir {
    //     dir 'libs'
    // }
}

dependencies {
    implementation "curse.maven:vampirism-233029:6544569"
    compileOnly "curse.maven:vampirism-integrations-282433:6842620"
    compileOnly "curse.maven:minecraft-comes-alive-reborn-535291:7278618"
    compileOnly "curse.maven:vampires-delight-939092:7223876"
    implementation "org.spongepowered:mixin:0.8.5"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

apply from: 'mcreator.gradle'
